### ISSUE TITLE
Stage presentation feedback

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/ATT#67]
A few of the slides start static or blank with no text while the speaker is to be transitioning to a new topic within the presentation. This feels wrong. The audience shouldn't ever see a blank screen. I wonder if for slide 3, we make the Revolution Better Together animate (like a center big to heading small), which would tie the transition into the next bullets better. And where there is a blank screen, to always animate in the top level content. Usually blank screens are left for dramatic effect, but I'm not sure our speakers will be effective at making that happen.

**Comment by saratheindustrious** [comment]
Agree. Here's my feedback. Going to email it to Gayle now, but tracking it here so I can use to review the next version.

- [ ] Slide 3 - animate in first bullet on page built (like page 9 does) 
- [ ] Slide 5 - need to feature discover stations somehow; I'm thinking maybe just showing [the homepage of one of them](https://www.dropbox.com/s/kxrld85hct0yv4s/discover-opus-0-home.jpg?dl=0) in a screen frame (can pull a generic frame from preso-ltb-overview.psd)
- [ ] Slide 6 - let's go back to full opacity on the top layer; I think the transparency is distracting
- [ ] Slide 12 - top layer full opacity
- [ ] Slide 16 - top layer full opacity
- [ ] Slide 17 - animate in first bullet on page built (like page 9 does)
- [ ] Slide 17 - text too close to margins; either reduce text size or make first bullet 2 lines
- [ ] Slide 19 - delete this slide
- [ ] Slide 20 - something is off with the masking of the nav bar; check the original comp
- [ ] Slide 20-23 - can we do a different animation from the "section headers" - maybe just have the comps slide L>R instead of revealing the text
- [ ] Slide 21 – Urgent Alerts - Change to “Urgent Messages” (this was in my feedback email yesterday)
- [ ] Slide 21 – Center horizontally main content in the screen
- [ ] Slide 21 – let's add a vertical iPad frame to match slide 20
- [ ] Slide 22 – Center horizontally main content in the screen
- [ ] Slide 22 – let's add a vertical iPad frame to match slide 20
- [ ] Slide 23 – Center horizontally main content in the screen (text is touching right edge)
- [ ] Slide 23 – Add white space to PDF
- [ ] Slide 28 - Speed up the animation of the first three, just a bit; maybe the faded background behind the devices could animate WITH the other elements instead of creating a pause between
- [ ] Slide 28-29 - the first three devices seem to shrink when we add the fourth during this slide transition; maybe just have them all on the same slide with a "click" animation to reveal the fourth to make this seamless?
- [ ] Slide 30 - top layer full opacity
- [ ] Slide 34 - not loving this animation; let's just have them all fade on together (instead of in sequence like we do earlier in the deck)
- [ ] Transition test between the last two slides: I think this is a crossfade; could we try instead fading content to blue and fade new content in? (vs. seeing them overlay each other briefly) And I don't think we 'll need transitions between video slides; we can double check that when we get them to place in.
